---
  - name: Playbook
    hosts: webservers
    become: yes
    become_user: root
    tasks:
      - name: Install apache httpd  (state=present is optional)
        ansible.builtin.apt:
          name: apache2
          state: present
      - name: ensure apache is running
        ansible.builtin.service:
          name: apache2
          state: started
          enabled: yes
